# gitlab ci/cd file for students repo:
# 1. grade students' tasks (and merge requests)
# 2. grade students' merge requests to tests repo
#
# should be configured to run as external ci/cd file (from public repo)
# students has developer role, so they can't change ci/cd settings, so the file is fixed

variables:
  GIT_DEPTH: 1
  GIT_STRATEGY: clone
  REF_DIR: /opt/shad


# Testing and Grading all tasks
grade:
  image: cr.yandex/crp9onavos88ug32d5r2/grader/sre-grader:14062024
  rules:
    # never run in public repo
    - if: $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
      when: never
    # never run on contributing branches
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      when: never
    # otherwise run always
    - when: on_success
  script:
    - cd /opt/shad && PYTHONPATH=grader python3 -m grader
  timeout: 10 minutes
