variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - release

deploy:
  only:
  - master
  tags:
  - docker
  stage: release
  script:
  - >
    curl -H "Authorization: Bearer ${TESTER_TOKEN}" -H "Content-Type: text/x-yaml; charset=utf-8" --data-binary @.course.yml https://manytask.sreweek.ru/api/update_course_config
  - >
    curl -H "Authorization: Bearer ${TESTER_TOKEN}" -H "Content-Type: text/x-yaml; charset=utf-8" --data-binary @.deadlines.yml https://manytask.sreweek.ru/api/update_deadlines
  # - docker pull cr.yandex/crp9onavos88ug32d5r2/grader/sre-build
  # - docker build -f testenv.docker -t cr.yandex/crp9onavos88ug32d5r2/grader/sre .
  # - docker push cr.yandex/crp9onavos88ug32d5r2/grader/sre:latest
